import React from 'react'
import Head from 'next/head'
import { css, cx } from '@emotion/css'

export default function Home() {
  const backColor = '#FFC312'
  const color = '#EA2027'
  return (
    <>
      <Head>
        <title>Ultimate App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div
        className={css`
          padding: 32px;
          color: ${color};
          font-size: 24px;
          text-align: center;
          border-radius: 4px;
          background-color: ${backColor};
            &:hover {
              color: white;
            }
        `}
      >
      Ultimate App Project
    </div>
      </main>
    </>
  )
}
