import React from 'react'
import Head from 'next/head'
import { useState } from 'react'
import { useRouter } from 'next/router'
import { useDispatch } from 'react-redux'
import actionTypes from '../configs/actionTypes'
import LayoutAuth from '../containers/LayoutAuth'
import FormControl from '../containers/FormControl'
import { InputEmail, InputPassword, Button, H2, Hyperlink } from '../components'

export default function Login() {
   const router = useRouter()
   const dispatch = useDispatch()
   const [formValue,setFormValue] = useState({})

   const handleSubmit = (event) => {
      if (event) event.preventDefault()
      console.log('handleSubmit',formValue)
      dispatch({
         type: actionTypes.LOGIN,
         logged: true,
         email: formValue.email
      })
      router.push('/')
   }

   const handleOnChange = (name,value) => {
      setFormValue({
         ...formValue,
         [name]: value,
      })
   }

   return (
      <>
         <Head>
            <title>ورود</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <LayoutAuth>
            <H2>به ریموت جابب خوش آمدید</H2>
            <form onSubmit={handleSubmit}>
               <FormControl>
                  <InputEmail onChange={(value) => handleOnChange('email',value)} placeholder='ایمیل'/>
               </FormControl>
               <FormControl>
                  <InputPassword onChange={(value) => handleOnChange('password',value)} placeholder='رمز عبور' />
               </FormControl>
               <FormControl>
                  <Button type='submit'>وارد شوید</Button>
               </FormControl>
               <Hyperlink href='/register' text='ثبت نام نکرده اید؟'>ثبت نام کنید</Hyperlink>
               <Hyperlink href='/forgot' text='رمز عبور خود را فراموش کرده اید؟'>فراموشی رمز عبور</Hyperlink>
            </form>
         </LayoutAuth>
      </>
   )
}
