import React from 'react'
import Head from 'next/head'
import { useState } from 'react'
import { useRouter } from 'next/router'
import LOGIN_ACTION from '../actions/index'
import LayoutAuth from '../containers/LayoutAuth'
import FormControl from '../containers/FormControl'
import { useDispatch, useSelector } from 'react-redux'
import { InputEmail, InputPassword, Button, H2, Hyperlink } from '../components'

export default function Login() {
   const router = useRouter()
   const dispatch = useDispatch()
   const [formValue,setFormValue] = useState({})
   const auth = useSelector((state) => state.auth )

   const handleSubmit = async (event) => {
      if (event) event.preventDefault()
      dispatch(LOGIN_ACTION())
      /*setTimeout(() => {
         router.push('/') 
      }, 5200);*/
   }

   const handleOnChange = (name,value) => {
      setFormValue({
         ...formValue,
         [name]: value,
      })
   }

   return (
      <>
         <Head>
            <title>ورود</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <LayoutAuth>
            <H2>به ریموت جابب خوش آمدید</H2>
            <form onSubmit={handleSubmit}>
               <FormControl>
                  <InputEmail onChange={(value) => handleOnChange('email',value)} placeholder='ایمیل'/>
               </FormControl>
               <FormControl>
                  <InputPassword onChange={(value) => handleOnChange('password',value)} placeholder='رمز عبور' />
               </FormControl>
               <FormControl>
                  <Button type='submit' loading={auth.loading}>وارد شوید</Button>
               </FormControl>
               <Hyperlink href='/register' text='ثبت نام نکرده اید؟'>ثبت نام کنید</Hyperlink>
               <Hyperlink href='/forgot' text='رمز عبور خود را فراموش کرده اید؟'>فراموشی رمز عبور</Hyperlink>
            </form>
         </LayoutAuth>
      </>
   )
}
