import React from 'react'
import Head from 'next/head'
import { useState } from 'react'
import LayoutAuth from '../containers/LayoutAuth'
import FormControl from '../containers/FormControl'
import { InputPassword, Button, H2 } from '../components'

export default function Reset() {
   const [formValue,setFormValue] = useState({})

   const handleSubmit = (event) => {
      if (event) event.preventDefault()
      console.log('handleSubmit',formValue)
   }

   const handleOnChange = (name,value) => {
      setFormValue({
         ...formValue,
         [name]: value,
      })
   }

   return (
      <>
         <Head>
            <title>تغییر کلمه عبور</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <LayoutAuth>
            <H2>می خواهید کلمه عبور خود را تغییر دهید؟</H2>
            <form onSubmit={handleSubmit}>
               <FormControl>
                  <InputPassword onChange={(value) => handleOnChange('email',value)} placeholder='کلمه عبور جدید'/>
               </FormControl>
               <FormControl>
                  <InputPassword onChange={(value) => handleOnChange('email',value)} placeholder='تکرار کلمه عبور جدید'/>
               </FormControl>
               <FormControl>
                  <Button type='submit'>تغییر</Button>
               </FormControl>
            </form>
         </LayoutAuth>
      </>
   )
}
